workspace(name = "helloworld")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# ===== Bazel skylib dependency =====
http_archive(
    name = "bazel_skylib",
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
)
# Check bazel version
load("@bazel_skylib//lib:versions.bzl", "versions")
versions.check("6.4.0")

# ===== Grpc dependency =====
# grpc v1.72.2, depend protobuf v30.0/v4.30.0/v6.30.0
http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/d6b42b2fd3e522a60318c7e2f2021219c6b5c470.tar.gz",
    ],
    strip_prefix = "grpc-d6b42b2fd3e522a60318c7e2f2021219c6b5c470",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()