workspace(name = "helloworld")

# Load all external repositories
load("//deps:repositories.bzl", "repositories")
repositories()

# Check bazel version
load("@bazel_skylib//lib:versions.bzl", "versions")
versions.check("6.4.0")

# Load grpc deps
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()