workspace(name = "helloworld")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# grpc v1.72.2, depend protobuf v30.0/v4.30.0/v6.30.0
http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/d6b42b2fd3e522a60318c7e2f2021219c6b5c470.tar.gz",
    ],
    strip_prefix = "grpc-d6b42b2fd3e522a60318c7e2f2021219c6b5c470",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()